CREATE TABLE dbo.Users (
  Id INT IDENTITY PRIMARY KEY,
  Username NVARCHAR(100) NOT NULL UNIQUE,
  PasswordHash NVARCHAR(200) NOT NULL,
  Roles NVARCHAR(200) NOT NULL DEFAULT 'user'
);

CREATE TABLE dbo.Items (
  Id INT IDENTITY PRIMARY KEY,
  UserId INT NOT NULL FOREIGN KEY REFERENCES dbo.Users(Id) ON DELETE CASCADE,
  Name NVARCHAR(100) NOT NULL
);